### ISSUE TITLE
Get 3D structure of polymer chain from smile

### ISSUE THREAD

**Issue by iuhgnor** [NREL/m2p#10]
After generating SMILES of a polymer chain by `m2p`, is there an easy way to embed the 3D structure for the polymer chain from SMILES? I have tried to embed a polymer chain with about two thousand atoms by `rdkit`, but it takes too long time. 
Could you give me some suggestions? Thanks in advance.

**Comment by wilsoa6** [comment]
I don't have a suggestion for 3D structure generation. I would rely on rdkit or some other package. You could try creating many small polymer chains in m2p using the `DP` (decrease) and `replicates` (increase) that might converge faster in the 3D algorithms, but this may impact whatever your results are as end group contributions will become larger for small chains.

**Comment by iuhgnor** [comment]
Thanks for your help.
