### ISSUE TITLE
Specific use-case: converting monomer SMILES values to polymer SMILES values (find polymerization points)

### ISSUE THREAD

**Issue by poojakedia** [NREL/m2p#7]
Hi,

I am working on a research project which entails collecting SMILES data of polymers, however, the databases where I extracted this information from do not provide the SMILES of the polymer rather only the monomer SMILES. There is not much information in the examples folder that depicts this kind of functionality in this package but I was wondering if I can use this package to perform the task of converting monomer SMILES to polymer SMILES.

**Comment by wilsoa6** [comment]
Yes, this is what m2p is designed to do. The polymer reactions that can be handled in PolyMaker().thermoplastics() are:

- polyamides
- polyesters
- polycarbonates
- polyvinyls/polyacrylates/polyolefins
- polyurethantes
- nonisocyanate polyurethanes (NIPU)
- polyimides

The following example shows how to conver monomer smiles (i.e. `smiles` in the dataframe) to polymer strings.
```
# create dataset
data = pd.DataFrame({'smiles':['C=C','C=CC','O=C(O)c1ccc(C(=O)O)cc1.OCCO','C=C.C=CC']},
                    index=['PE','PP','PET','PE-co-PP'])

# get monomers from smiles strings
data['monomers'] = data.smiles.apply(lambda s: pm.get_monomers(s))

# polymerize 
data = pm.thermoplastic(data,DP=10, mechanism='all',replicate_structures=3)
```

**Comment by poojakedia** [comment]
Hi, I was wondering if you package can be used to find the polymerization points on the smiles strings represented by *. I am aware that the package returns the polymer SMILES to the degree of polymerization specified but for my purposes I need to have values with the polymerization points of the SMILES.
