### ISSUE TITLE
Polymerization Points using Package

### ISSUE THREAD

**Issue by poojakedia** [NREL/m2p#9]
Hi, I was wondering if your package can be used to find the polymerization points on the smiles strings represented by *. I am aware that the package returns the polymer SMILES to the degree of polymerization specified but for my purposes I need to have values with the polymerization points of the SMILES.

**Comment by wilsoa6** [comment]
In the PolyMarker there are dictionaries which have smarts strings for function groups (`polymaker().smiles_templates`) and for the smarts reactions (`polymaker().reactions`). I dont think this is exactly what you are looking for, but you can probably create templates based on the smarts strings.
